version: '3'
services:
  vite:
    container_name: vite
    image: node:16-buster-slim
    working_dir: /var/local/app
    volumes:
      - type: bind
        source: ./
        target: /var/local/app
        consistency: cached
    command: /bin/sh -c "yarn cache clean && yarn install && yarn build --watch"
    env_file: .env

  nginx:
    container_name: nginx
    image: nginx:latest
    volumes:
      - type: bind
        source: ./config/nginx/default.conf
        target: /etc/nginx/conf.d/default.conf
      - type: bind
        source: ./log/nginx
        target: /var/log/nginx
      - type: bind
        source: ./public
        target: /usr/share/nginx/html
    ports:
      - 8080:80
    depends_on:
      - vite
    env_file: .env
